version: "2"
services:
    client:
        build: ./client
        container_name: chaosClient
        ports:
            - 80:80
        depends_on:
            - api
    api:
        build: ./api
        container_name: chaosApi
        depends_on: 
            - db
    db:
        image: mongo
        container_name: chaosDb
        volumes:
            - /var/lib/chaos:/data/db
